#!/bin/bash

echo "====================================="
echo "   🚀 Deploy PartsFinda"
echo "====================================="
echo ""
echo "Instructions:"
echo "1. Copy the command below"
echo "2. Replace YOUR_TOKEN with your GitHub token"
echo "3. Run it"
echo ""
echo "====================================="
echo ""
echo "COMMAND TO RUN:"
echo ""
echo "git push https://YOUR_TOKEN@github.com/seangolding876/PartsFinda.git master:main"
echo ""
echo "====================================="
echo ""
echo "Example: If your token is ghp_abc123, the command would be:"
echo "git push https://ghp_abc123@github.com/seangolding876/PartsFinda.git master:main"
echo ""
